using Loan.Domain.Common;

namespace Loan.Domain.Recommendations;

public enum RecommendationType
{
    PendingInformation,
    Approve,
    ReferToHuman,
    Reject
}

public enum RecommendationStatus
{
    DraftPreparedBySystem,
    PendingOfficerReview,
    ApprovedByOfficer,
    ReturnedForInfo,
    RejectedByOfficer
}

public class RecommendationCitation
{
    public string DocumentTitle { get; }
    public string PolicyVersion { get; }
    public string SectionOrPage { get; }
    public string Excerpt { get; }

    public RecommendationCitation(string documentTitle, string policyVersion, string sectionOrPage, string excerpt)
    {
        if (string.IsNullOrWhiteSpace(documentTitle)) throw new ArgumentException("Document title is required.", nameof(documentTitle));
        if (string.IsNullOrWhiteSpace(policyVersion)) throw new ArgumentException("Policy version is required.", nameof(policyVersion));

        DocumentTitle = documentTitle;
        PolicyVersion = policyVersion;
        SectionOrPage = sectionOrPage ?? "N/A";
        Excerpt = excerpt ?? string.Empty;
    }
}

public class RecommendationAuditEntry
{
    public string Action { get; }
    public string PerformedBy { get; }
    public DateTime TimestampUtc { get; }
    public string Notes { get; }

    public RecommendationAuditEntry(string action, string performedBy, DateTime timestampUtc, string notes)
    {
        Action = action;
        PerformedBy = performedBy;
        TimestampUtc = timestampUtc;
        Notes = notes ?? string.Empty;
    }
}

public class Recommendation
{
    public string RecommendationId { get; }
    public RecommendationType DecisionRecommendation { get; private set; }
    public RecommendationStatus Status { get; private set; }
    public double RiskScore { get; }                      // 0.0 (low risk) to 1.0 (high risk)
    public string SummaryReasoning { get; }
    public IReadOnlyList<RecommendationCitation> Citations { get; }
    public IReadOnlyList<string> PolicyViolations { get; }
    public IReadOnlyList<string> MissingEvidenceItems { get; }
    public IReadOnlyList<RecommendationAuditEntry> AuditTrail => _auditTrail.AsReadOnly();
    
    public string? ApprovedByOfficerId { get; private set; }
    public DateTime? ApprovedAtUtc { get; private set; }
    public string? OfficerDecisionNotes { get; private set; }

    private readonly List<RecommendationAuditEntry> _auditTrail = new();

    public Recommendation(
        string recommendationId,
        RecommendationType decisionRecommendation,
        double riskScore,
        string summaryReasoning,
        IEnumerable<RecommendationCitation> citations,
        IEnumerable<string> policyViolations,
        IEnumerable<string> missingEvidenceItems,
        DateTime createdAtUtc,
        string createdBySystemAgent = "RecommendationAgent")
    {
        if (string.IsNullOrWhiteSpace(recommendationId)) throw new ArgumentException("RecommendationId is required.", nameof(recommendationId));

        RecommendationId = recommendationId;
        RiskScore = Math.Clamp(riskScore, 0.0, 1.0);
        SummaryReasoning = summaryReasoning ?? string.Empty;
        Citations = citations?.ToList().AsReadOnly() ?? new List<RecommendationCitation>().AsReadOnly();
        PolicyViolations = policyViolations?.ToList().AsReadOnly() ?? new List<string>().AsReadOnly();
        MissingEvidenceItems = missingEvidenceItems?.ToList().AsReadOnly() ?? new List<string>().AsReadOnly();

        // BR-06: Recommendation with missing mandatory evidence remains PendingInformation
        if (MissingEvidenceItems.Count > 0)
        {
            DecisionRecommendation = RecommendationType.PendingInformation;
        }
        else
        {
            DecisionRecommendation = decisionRecommendation;
        }

        Status = RecommendationStatus.DraftPreparedBySystem;
        RecordAudit("DraftPrepared", createdBySystemAgent, createdAtUtc, "Draft recommendation generated by system specialist agents.");
    }

    /// <summary>
    /// BR-07: Only an authorized loan officer may approve/reject/return recommendation status.
    /// </summary>
    public void ApproveByOfficer(string officerId, string decisionNotes, DateTime timestampUtc)
    {
        if (string.IsNullOrWhiteSpace(officerId)) throw new ArgumentException("Officer ID is required for approval.", nameof(officerId));
        if (Status == RecommendationStatus.ApprovedByOfficer) throw new InvalidApplicationStateException("Recommendation is already approved.");

        Status = RecommendationStatus.ApprovedByOfficer;
        ApprovedByOfficerId = officerId;
        ApprovedAtUtc = timestampUtc;
        OfficerDecisionNotes = decisionNotes;

        RecordAudit("OfficerApproved", officerId, timestampUtc, decisionNotes);
    }

    public void RejectByOfficer(string officerId, string decisionNotes, DateTime timestampUtc)
    {
        if (string.IsNullOrWhiteSpace(officerId)) throw new ArgumentException("Officer ID is required for rejection.", nameof(officerId));

        Status = RecommendationStatus.RejectedByOfficer;
        ApprovedByOfficerId = officerId;
        ApprovedAtUtc = timestampUtc;
        OfficerDecisionNotes = decisionNotes;

        RecordAudit("OfficerRejected", officerId, timestampUtc, decisionNotes);
    }

    public void ReturnForMoreInformation(string officerId, string requestedItemsNote, DateTime timestampUtc)
    {
        if (string.IsNullOrWhiteSpace(officerId)) throw new ArgumentException("Officer ID is required.", nameof(officerId));

        Status = RecommendationStatus.ReturnedForInfo;
        ApprovedByOfficerId = officerId;
        OfficerDecisionNotes = requestedItemsNote;

        RecordAudit("ReturnedForInfo", officerId, timestampUtc, requestedItemsNote);
    }

    private void RecordAudit(string action, string performedBy, DateTime timestampUtc, string notes)
    {
        _auditTrail.Add(new RecommendationAuditEntry(action, performedBy, timestampUtc, notes));
    }
}
